### ISSUE TITLE
Last page doesn't write into history on every site.

### ISSUE THREAD

**Issue by GoroFourArms** [hoothin/UserScripts#276] opened 2023-01-10 00:37 UTC
**Describe the bug**
Last page doesn't write into history on every site.

**Desktop (please complete the following information):*
windows 10
firefox 108.0.2 (64-bit
violentmonkey 2.13.5

**Comment by hoothin** [comment] 2023-01-10 01:44
Take a look at the "Write history immediately after splicing, otherwise write after browsing".

**Comment by GoroFourArms** [comment] 2023-01-10 02:11
I noticed it doesn't write page 2 then pushes it to the last page. I tried "history": 2 but it doesn't solve it.

**Comment by hoothin** [comment] 2023-01-10 02:46
Did you check the option "Write history immediately after splicing, otherwise write after browsing"?
Maybe you can post a example here for me to realize what you said.

**Comment by GoroFourArms** [comment] 2023-01-10 02:58
i only see Write history after page turning and i tried both checked and unchecked.

**Comment by hoothin** [comment] 2023-01-10 03:00
Have you updated to the latest version?

**Comment by GoroFourArms** [comment] 2023-01-10 03:02
sorry for wasting your time, i thought it was auto updating i must have turned it off when i was reverting to solve a previous issue.

**Comment by GoroFourArms** [comment] 2023-03-08 01:05
I'm having trouble figuring out how to restore functionality to  "spoilers" loaded pages on this site https://www.scribblehub.com/read/560987-battle-across-the-omniverse/chapter/561026/

**Comment by hoothin** [comment] 2023-03-08 01:19
<pre name="pagetual">
{
    "name": "scribblehub",
    "url": "^https://www\\.scribblehub\\.com/read",
    "pageElement": "#chp_raw",
    "nextLink": "a.btn-next",
    "action": 0,
    "pageAction": "eles.forEach(ele=>{[].forEach.call(ele.querySelectorAll('.sp-head'),sp=>{sp.onclick=e=>{sp.nextElementSibling.classList.toggle('folded')}})})"
}
</pre>

And you can use "force to join" instead.

**Comment by GoroFourArms** [comment] 2023-03-08 02:13
Thanks for your help.

**Comment by GoroFourArms** [comment] 2023-04-29 18:20
https://dreambigtl.blogspot.com/2023/04/adopting-disaster-2-2.html sorry I'm stumped how to do this site.

**Comment by hoothin** [comment] 2023-04-30 01:18
<pre name="pagetual">
{
    "name": "dreambigtl",
    "url": "^https?://dreambigtl\\.blogspot\\.com/",
    "example": "https://dreambigtl.blogspot.com/2023/04/adopting-disaster-3-1.html",
    "nextLink": "//a[text()='Next Chapter']",
    "pageElement": ".post-body",
    "action": 0
}
</pre>

**Comment by GoroFourArms** [comment] 2023-04-30 17:16
It still doesn't work. I think its because the next link goes to https://www.novelupdates.com/extnu/7047665/

**Comment by GoroFourArms** [comment] 2023-04-30 17:19
I was also wondering if names and examples are necessary cause i never use them.

**Comment by GoroFourArms** [comment] 2023-05-01 21:13
I turned on autorun and its working now. I don't know why,

**Comment by hoothin** [comment] 2023-05-12 00:20
![image](https://github.com/hoothin/UserScripts/assets/5361213/65a5edc7-59c8-4059-8160-7379b867114a)
What does "Page 2 gets deleted" mean?
I tested your rule but didn't find any issue with that. Just lose a `\` before `\d+`.

**Comment by GoroFourArms** [comment] 2023-05-12 00:39
I'm sorry its working now. This is so frustrating when i waste your time.  I was using next link //a[contains(text(),'ext')] before. Most sites that have two of the same link causes problems for me.  So when i go to page 3 it would delete and only show page 2.

**Comment by GoroFourArms** [comment] 2023-05-12 00:59
There's a weird issue because two novels are using the same web address. Its happening again. I can't get more then 3 pages before it switches novels.

**Comment by GoroFourArms** [comment] 2023-05-12 01:02
Ah one novel uses /?=kangmin%2F the other uses /?=kangmin/

**Comment by hoothin** [comment] 2023-05-12 01:07
Any link could post here for me to check?

**Comment by GoroFourArms** [comment] 2023-05-12 01:21
https://cyborg-tl.com/kangmin/chapter-83-2/?=kangmin/
https://cyborg-tl.com/kangmin/chapter-83/?=kangmin/

these two novels get mixed up so i guess my link by url wouldnt work

**Comment by hoothin** [comment] 2023-05-12 01:26
So why not try `.pagi-next>a` for nextLink?

**Comment by GoroFourArms** [comment] 2023-05-12 01:30
So when I use that on [ link ](https://cyborg-tl.com/kangmin/chapter-83-2/?=kangmin/) when i go to try for chapter 85 it blinks and shows chapter 84.

**Comment by hoothin** [comment] 2023-05-12 01:35
![image](https://github.com/hoothin/UserScripts/assets/5361213/775f2f4d-c4e5-4f46-88a1-e8171c5ae58f)

Sorry I can't realize the issue what you say😂.

**Comment by GoroFourArms** [comment] 2023-05-12 01:37
There is always an issue like this when there are two links like upper and lower bar  although this is a first for me usually it just loads an extra last page.

**Comment by hoothin** [comment] 2023-05-12 01:43
Which two? Have you tried `.pagi-next>a`? I tested with that selector and didn't find any issue with wrong links.

**Comment by GoroFourArms** [comment] 2023-05-12 01:45
"url": "^https://cyborg-tl\\.com",
        "pageElement": "article > .entry-content",
        "nextLink": ".pagi-next>a",
        "action": 0

So there are two links one is from entry-pagination the other is entry-pagination.jojo even if i select just one it still has the same problem.

**Comment by GoroFourArms** [comment] 2023-05-12 01:54
I think i found out what it is I had 

Write history after page turning
  | Write history immediately after splicing, otherwise write after browsing

both checked.

**Comment by hoothin** [comment] 2023-05-12 02:00
So which page have the different links among elements matched ".pagi-next>a"?

**Comment by hoothin** [comment] 2023-05-12 02:06
Ah I see, there is no next on "https://cyborg-tl.com/kangmin/chapter-85-2/?=kangmin/" but you want to get "https://cyborg-tl.com/kangmin/chapter-86-2/?=kangmin/" from that?
You can't get right link with the history writing. Am I right?
I'll fix that.

**Comment by GoroFourArms** [comment] 2023-05-12 02:14
I unchecked  history after page turning and i think it fixed it. I wasn't sure if they conflicted each other.

**Comment by hoothin** [comment] 2023-05-12 02:34
I checked again, I think there is no conflict between these.
If you use nextLink, you can't get link on "https://cyborg-tl.com/kangmin/chapter-85-2/?=kangmin/" as the link isn't right.
If you use nextLinkByUrl, you can't get link on "https://cyborg-tl.com/kangmin/chapter-85-2/?=kangmin/" as "chapter-86-2" point to null.

Maybe you can try `.pagi-next>a[href^="http"]`;

**Comment by GoroFourArms** [comment] 2023-05-12 23:04
I don't know what to tell you other than i believe its not an issue with the next link. I tried a lot of different nextlinks and it comes up with the same issue but when i unchecked page turning history. It fixed the issue.

**Comment by GoroFourArms** [comment] 2023-05-12 23:16
I think there was a conflict with the autopagerize lazyload assistant script i never had a need to turn it off before but now i think thats the issue.

**Comment by GoroFourArms** [comment] 2023-05-13 00:08
On a seperate note when i disable a site the enable button doesnt show. I tried to fix it on autorun but now that i disable it on autorun its not showing anymore.

**Comment by hoothin** [comment] 2023-05-13 00:11
Sorry I can't reproduce that issue, I need the exact url and the rule you are using. Details of the console log is helpful too.

**Comment by GoroFourArms** [comment] 2023-05-13 00:19
It happens on every site. I essentially cant use the script without autorun on and without hitting the disable button. Where is the console log?

**Comment by GoroFourArms** [comment] 2023-05-13 00:24
I'm going to refresh my firefox i hope that fixes the issues.

**Comment by hoothin** [comment] 2023-05-13 00:30
I means the issue on cyborg-tl.com. 
About the "enable button", what do you mean? 
I didn't make any "enable button", do you mean the "side controller"? If you disabled in a site, you need to enable it in command menu of tampermonkey.

**Comment by GoroFourArms** [comment] 2023-05-13 01:01
The enable issue is working on
    1.9.36.6
and broken on
[v1.9.36.7]

**Comment by hoothin** [comment] 2023-05-13 01:03
Yes, I have fixed the enable issue. Just wait for next version I'll post later.
All I need is the information about issue of cyborg-tl.com now.

**Comment by GoroFourArms** [comment] 2023-05-13 01:09
I refreshed my firefox and not using custom rules seems to be working now.

**Comment by GoroFourArms** [comment] 2023-06-03 05:20
just a feature suggestion, Simply entering a web address to append to the bottom . Like if there's a broken link and you just want to quickly add the page. Or like I don't know if there is something on firefox where you can drag a tab on another and append it to the bottom.

**Comment by GoroFourArms** [comment] 2023-06-03 05:27
just a feature suggestion, Simply entering a web address to append to the bottom . Like if there's a broken link and you just want to quickly add the page. Or like I don't know if there is something on firefox where you can drag a tab on another and append it to the bottom. Also if there is a TOC and copy a bunch of links to append to each other.

**Comment by hoothin** [comment] 2023-06-03 06:04
That won't work if the pages are not in the same origin. And style of each page is a question, they maybe tangled together. If you can handle these issues, it's easy to add this feature.

**Comment by GoroFourArms** [comment] 2023-07-06 17:30
I can't get the autoclick to work on this site
https://travistranslations.com/rss/y27463e403/

{
    "url": "^https?://travistranslations\\.com/",
    "pageElement": "div.reader-content",
    "autoClick": ".reader-content a",
    "action": 1,
    "PinUrl": true,
    "nextLink": ".next"
}

I also don't know what to do with this https://ncs69.blogspot.com/2023/06/milimos-saga-reincarnation-chronicle-of_30.html

**Comment by hoothin** [comment] 2023-07-07 00:54
You cannot click on that element because you have to wait for 3 seconds. Try to make an extra rule for the middle page like:
```
    {
        "url": "^https?://travistranslations\\.com/",
        "include": ".reader-content a:not(a[href])",
        "autoClick": ".reader-content a",
        "waitElement": ".reader-content a[href]"
    },
    {
        "url": "^https?://travistranslations\\.com/",
        "exclude": ".reader-content a:not(a[href])",
        "pageElement": "div.reader-content",
        "autoClick": ".reader-content a",
        "action": 1,
        "PinUrl": true,
        "nextLink": ".next",
        "waitElement": "!.reader-content a:not(a[href])"
    }
```

**Comment by hoothin** [comment] 2023-07-07 01:03
About your second link, I haven't seen any nextLink on the page. If you want to read all from one page, try my [Download All content](https://greasyfork.org/scripts/25068), use custom download with `.post-title>a`.

**Comment by GoroFourArms** [comment] 2023-07-10 16:35
That script is something I wanted for years but never found.

**Comment by GoroFourArms** [comment] 2023-08-17 01:16
download all content is fantastic except i get double spaces between each word lol. I have to replace them.

**Comment by hoothin** [comment] 2023-08-17 02:53
Fixed in v.2.7.3.20.

**Comment by GoroFourArms** [comment] 2023-08-19 00:54
Thanks. I was wondering if it was possible to delete pages and pause.  Like sometimes i didn't yet put a stop action and I want to get rid of the bottom page.

**Comment by hoothin** [comment] 2023-08-19 05:47
You can delete pages and pause through double click the side controller with v.1.9.36.48

**Comment by GoroFourArms** [comment] 2023-09-25 17:14
https://www.lightnovelworld.com/novel/the-editor-is-the-novels-extra-1181/chapter-2-30041322
this site doesn't load pagetual. I can get it to load if i block all scripts with ublock but its still only loads one page sometimes.

**Closed** 2023-10-19 12:00 UTC
